packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
  - "automations/make/*"
  - "automations/power-platform/*"
  - "automations/zapier/*"
  - "automations/n8n/nodes/*"

allowBuilds:
  esbuild: true
  protobufjs: set this to true or false

catalogMode: strict

cleanupUnusedCatalogs: true

injectWorkspacePackages: true

linkWorkspacePackages: true

savePrefix: ""
